### ISSUE TITLE
Can't connect because I'm behind corporate proxy

### ISSUE THREAD

**Issue by renato-bohler** [foxythemes/jira-cli#14]
Hey! First of all, this project looks awesome :smile: but I'm trying to use this CLI at work, but the proxy is messing everything up.

I've installed `jira-cl`, configured my credentials via `jira` command and when I type `jira i` I'm given the following error message:

```
> jira i
> (node:14832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'length' of undefined
> (node:14832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I try `jira u` the error message is slightly different:

```
> jira u
> (node:14871) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 407 - "<PROXY FAIL PAGE CONTENT>"
```

**Comment by miguelmich** [comment]
Hello @renato-bohler, thanks for your support! I see... we're using this lib as a base to make the API requests: https://github.com/jira-node/node-jira-client and in this case, I think you should make the API calls through your proxy, but I'm afraid that this lib doesn't support it currently: https://github.com/jira-node/node-jira-client/issues/92

**Comment by renato-bohler** [comment]
They don't support proxy officially, but they use `request` (from `request-promise`) which does support proxy.

Fortunately, we could pass the `request` parameter as an option to `node-jira-client`: see [jira.js at line 25](https://github.com/jira-node/node-jira-client/blob/9ac7e6027a2ad488d79f0556ff04600abd5447f2/src/jira.js#L25).

In fact, I've forked this repo and made I work through proxy. I know this is not the best solution to the problem, but here's what I've done:
- add the dependency `request-response`;
- check for a `proxy` key on the config file;
- mount and pass a proxied `request` to connect to `node-jira-client` if that key is set.

Here's the commit on the fork: https://github.com/renato-bohler/jira-cli/commit/7353596592adfdbc7bc822b8bea700f580e38d96.

I'm willing to add an extra config option to set the proxy via CLI and I can submit a PR if you think that's ok.

**Comment by miguelmich** [comment]
that's awesome, sure a PR would be great!

Thanks @renato-bohler :)
