### ISSUE TITLE
SSO accounts

### ISSUE THREAD

**Issue by benharri** [foxythemes/jira-cli#17]
I'm not able to authenticate with the current user/pass combo since my jira instance uses SSO. How do I log in with SSO?

**Comment by miguelmich** [comment]
Hello @benharri, can you please take a look to this: https://community.atlassian.com/t5/Jira-questions/REST-SSO-Atlassian-Account-JIRA/qaq-p/580736 it seems that the login with password still works in the API, maybe using your email instead your username? give it a try and let me know :)

**Comment by benharri** [comment]
@miguelmich that still didn't work. I'll give it another try tomorrow.

**Comment by rmaclean-ee** [comment]
You can use API tokens. I used my SSO email address and the token as the password
https://confluence.atlassian.com/x/Vo71Nw

**Comment by benharri** [comment]
Oh the API token worked! Just got a chance to try it. 

Thanks!
