### ISSUE TITLE
Jira connect does not work properly

### ISSUE THREAD

**Issue by markaltmann** [foxythemes/jira-cli#21]
I need to connect to a Jira behind  a corporate firewall. Additionally, there are separate instances via a special suffix. I assume that suffix has to be appended. 
Also i had to manually add the https protocol, as the config did not set it in the wizard. Also the setting later did work not always right. Anyways: If i then connect, i get the following error message, but no detailed message:

Error retreiving issues list: 401: Unable to connect to JIRA during search.

Is there a way to get a better error log?

Thx

**Comment by miguelmich** [comment]
@markaltmann, we already merged a PR to set up a proxy connection in #15, you can set your proxy like this `jira config proxy [proxy address]`

Let me know if it works for you :)
