### ISSUE TITLE
jira-cli does not exit after opening an issue

### ISSUE THREAD

**Issue by finferflu** [foxythemes/jira-cli#22]
Hi,

I've noticed that when I issue `jira o <issue>`, the process doe not terminate. I have to manually quit it with CTRL+C. Is that the expected behaviour?

Thank you.

**Comment by miguelmich** [comment]
Strange, what OS and terminal are you using?

**Comment by finferflu** [comment]
It's iTerm2 on macOS 10.14.1.

**Comment by miguelmich** [comment]
@finferflu I just pushed a new release fixing this issue, can you please update it and tell me if it works good for you? :)

**Comment by finferflu** [comment]
@miguelmich thanks very much for that, however, I can't find version 1.2.0 on NPM.

**Comment by finferflu** [comment]
@miguelmich no problem, I was able to install the newer version, as I can confirm that the issue has been resolved. Thanks for the prompt fix!
