### ISSUE TITLE
Support for searching issues passing a JQL query

### ISSUE THREAD

**Issue by sm13** [foxythemes/jira-cli#26]
I'm just proposing that a feature be added to pass queries to commands like `jira i` or `jira s` to filter the results. Perhaps something like:
` jira i -q "project in (P1, P2) and type in (task, \"User Story\") order by key asc" `

I admit I don't know if this is possible through the API.

**Comment by sm13** [comment]
After a closer look, I believe Issue #19 solves this.

**Comment by sclarkso** [comment]
unfortunately it was never merged.
