### ISSUE TITLE
Spotted a problem in the documentation

### ISSUE THREAD

**Issue by bokub** [foxythemes/jira-cli#29]
In [this part](https://docs.jiracli.com/#introduction-examples) of the documentation, it says the command to list users is `jira issue` or `jira i`.

![image](https://user-images.githubusercontent.com/17952318/53552572-e73aa400-3b3b-11e9-8128-e7c39526dbce.png)

I would have fixed it but I cannot find the repository for the documentation.

**Comment by arnaudvalle** [comment]
Hello @miguelmich - I spotted a couple typos in the documentation site as well. 
Is there any way you could share the documentation site repository so people could contribute to it? I'd be happy to give a hand.

**Comment by miguelmich** [comment]
Yeah! thanks for the report, I'm currently moving it to Github pages inside this repository, I'm almost done, I'll let you know once it's up and running for sure :)

**Comment by miguelmich** [comment]
Hello guys, sorry for the delay, I finally managed to move the docs site to the repo using Hugo, you can now contribute to the documentation, just run `npm install` and then `npm run docs` you'll be able to access locally through http://localhost:1313/ 

You'll find the documentation sections here: https://github.com/foxythemes/jira-cli/tree/master/docs/content/home

I already fixed this issue, but the HTTPS certificate is currently being issued at the moment and it could take up to 24h, after that it should be available in the documentatio site.

Thanks again :)

**Comment by miguelmich** [comment]
I think the new documentation site it's working now with the new certificate, sorry for the typos and the drafting in general, at that time I was more focused on the styles that I didn't check the full content, hopefully, with this change it'll be easy to improve the overall documentation content.

**Comment by bokub** [comment]
Fixed by e92427d97d3949e821a216c31c99db39a267c391& 42cfc4c372e77d79b642a19915c2b2a520723a49 🎉
