### ISSUE TITLE
jira create hangs after prompting in powershell/cmd (works via bash)

### ISSUE THREAD

**Issue by feelingsofwhite** [foxythemes/jira-cli#31]
To be clear doesnt appear windows platform per se, as using bash via windows works fine.

Commands like "jira search", etc, work fine via powershell or cmd.exe

1. Invoke "jira create"
2. jira prompts for "? Project: "  
3. Accept default choice, press Enter
ACTUAL
---> appears to "hang", any keyboard input appears ignored.  
---> ctrl+break will lead to "terminate batch job (y/n)" 
EXPECTED
---> accepts value and leads to next prompt

Interestingly... when I first attempted and ran "jira" and it began initial config it led me through all the prompts and only hung after the very last one.  Pressing ctrl+break aborted it, but the "~/.jira-cli.json" had been successfully created.  This seems relevant in case it's a more generic issue with the "prompt the user"

**Comment by miguelmich** [comment]
Hello @feelingsofwhite, sorry for the late reply (I've been busy), that seems to be a problem with interactive mode lib, I'll check if it's related specifically with our options

**Comment by miguelmich** [comment]
I think this issue is already solved with the last update, can you please check with `v1.2.1`? thanks :)

**Comment by miguelmich** [comment]
Let me know if you're still having this issue so I'll re-open it
