### ISSUE TITLE
Basic auth fails

### ISSUE THREAD

**Issue by snowe2010** [foxythemes/jira-cli#35]
Like #23 my login is failing, but unlike #23 a reset of the password doesn't work. 

Currently I am encountering the same issue, where all attempts at logging in with basic auth is failing over curl. I've tried resetting my password, using curl, but it appears that basic auth fails with my org. Is there any way you could add support for api keys? I think that might fix the issue.

**Comment by miguelmich** [comment]
Sure, you can use API token as password, we need to update the docs: https://confluence.atlassian.com/cloud/api-tokens-938839638.html

**Comment by snowe2010** [comment]
Fantastic! Thank you! (I did not see that in the atlassian docs the first time I looked sorry about that).
