### ISSUE TITLE
Transition name is ignored when passed to `jira i <name> --transition`

### ISSUE THREAD

**Issue by dancrumb** [foxythemes/jira-cli#38]
I would expect the following command to transition my issue to "In Progress"

```
jira i OHANA-1105 --transition "In Progress"
```

However, it does not... I am just presented with a list of transitions and can select one.

**Comment by dancrumb** [comment]
Just a gentle nudge on this.

I'm happy to provide development assistance as automating our JIRA workflow is a valuable thing to us.

**Comment by miguelmich** [comment]
@dancrumb sure, PRs are always welcome :)

**Comment by dancrumb** [comment]
PR #39 is ready for your review 🙂

**Comment by Trimud** [comment]
Hi @miguelmich,

can we get this PR merged, please? It's a blocker for me to use this package in the context of Github Actions for example.

Thank you

**Comment by oscardemoya** [comment]
Hi @miguelmich When there would be a new release so we can get this fix from npm?
